### ISSUE TITLE
keymods not exported in wasabi module

### ISSUE THREAD

**Issue by dmoisset** [lordmauve/wasabi2d#18]
By reading https://wasabi2d.readthedocs.io/en/stable/events.html#keymods one would understand that `wasabi.keymods` is available as an importble enum, same as `wasabi.keys`, `wasabi.mouse` ; however it's actually inside `wasabi.constants`.

Should this be fixed by also exporting `keymods` in `wasabi/__init__.py`, or should the documentation be changed to say that `keymods` is elsewhere?

**Comment by lordmauve** [comment]
I think `keymods` should be in `wasabi2d/__init__.py`.
