### ISSUE TITLE
Wasabi doesn't update sprites unless they've moved

### ISSUE THREAD

**Issue by AnthonyBriggs** [lordmauve/wasabi2d#55]
I noticed this last night while I was porting my alien joypad demo from Pygame Zero to Wasabi. If you update a sprite's image but not it's position, then Wasabi will keep displaying the old image. I'm assuming this is due to a caching optimisation somewhere. This is on the most recent Wasabi2D from pip, running on Windows 10, installed last night.

You can see this in action in the demo [here](https://github.com/AnthonyBriggs/wasabi2d-demo/blob/master/alien.py#L94). When the sprite stops moving, it isn't updated and keeps the old run or jump image. Moving the sprite, even by 0.1, seems to force a refresh. 

Let me know if you need a simpler replication and I can rig one up.

**Comment by lordmauve** [comment]
Fixed in 13dc3b3.
