### ISSUE TITLE
What version of Opengl does wasabi2d need at least?

### ISSUE THREAD

**Issue by streetartist** [lordmauve/wasabi2d#67]
I know wasabi2d is using OpenGL.What version of Opengl does wasabi2d need at least?

**Comment by einarf** [comment]
Looking at the source it seems to be 4.1 : https://github.com/lordmauve/wasabi2d/blob/035f1de115088830992a8ae621c8d18798decd85/wasabi2d/scene.py#L168

**Comment by streetartist** [comment]
I know and I think You should Write it in the ReadMe.

**Comment by einarf** [comment]
> I know and I think You should Write it in the ReadMe.

Make a pull request? 😃

**Comment by lordmauve** [comment]
Fixed in #69.
